baseURL = 'https://r41nm4k3r.github.io/Coded4you/'
languageCode = 'en-us'
title = 'Code For You Web Services'
theme = 'goodforyou-theme'

[params]
  # GitHub Pages specific settings
  githubRepo = 'r41nm4k3r/Code4you'

